<?php
/* Template Name: Contact Page */
get_header(); ?>
<div class='page-content'>
<!-- wp:uagb/container {"block_id":"91a1a3a6","innerContentCustomWidthDesktop":1200,"alignItemsDesktop":"stretch","alignItemsTablet":"stretch","alignItemsMobile":"stretch","backgroundType":"image","backgroundImageDesktop":{"id":1674,"title":"colored-powders-and-brush-1749452","filename":"colored-powders-and-brush-1749452.jpeg","url":"https://shop900.rf.gd/wp-content/uploads/2025/05/colored-powders-and-brush-1749452.jpeg","link":"https://shop900.rf.gd/colored-powders-and-brush-1749452/","alt":"Colorful makeup powders and brushes in an artistic flat lay composition.","author":"0","description":"Colorful makeup powders and brushes in an artistic flat lay composition.","caption":"","name":"colored-powders-and-brush-1749452","status":"inherit","uploadedTo":0,"date":1746689141000,"modified":1746689141000,"menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop900.rf.gd/wp-includes/images/media/default.svg","dateFormatted":"8 مايو، 2025","nonces":{"update":false,"delete":false,"edit":false},"editLink":false,"meta":false,"authorName":"(لا مؤلف)","filesizeInBytes":163718,"filesizeHumanReadable":"160 كيلوبايت","context":"","height":945,"width":700,"orientation":"portrait","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://shop900.rf.gd/wp-content/uploads/2025/05/colored-powders-and-brush-1749452-150x150.jpeg","orientation":"landscape"},"medium":{"height":300,"width":222,"url":"https://shop900.rf.gd/wp-content/uploads/2025/05/colored-powders-and-brush-1749452-222x300.jpeg","orientation":"portrait"},"full":{"url":"https://shop900.rf.gd/wp-content/uploads/2025/05/colored-powders-and-brush-1749452.jpeg","height":945,"width":700,"orientation":"portrait"}},"compat":{"item":"","meta":""}},"backgroundColor":"","backgroundImageColor":"var(--ast-global-color-7)","topPaddingDesktop":180,"bottomPaddingDesktop":160,"leftPaddingDesktop":40,"rightPaddingDesktop":40,"topPaddingTablet":140,"bottomPaddingTablet":100,"leftPaddingTablet":32,"rightPaddingTablet":32,"topPaddingMobile":120,"bottomPaddingMobile":100,"leftPaddingMobile":24,"rightPaddingMobile":24,"paddingLink":false,"topMarginDesktop":0,"bottomMarginDesktop":0,"leftMarginDesktop":0,"rightMarginDesktop":0,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"marginLink":false,"variationSelected":true,"rowGapTablet":0,"rowGapMobile":0,"columnGapTablet":0,"columnGapMobile":0,"isBlockRootParent":true,"overlayType":"color","overlayOpacity":0.7,"textColor":"","equalHeight":true} -->
<div class="wp-block-uagb-container uagb-block-91a1a3a6 alignfull uagb-is-root-container"><div class="uagb-container-inner-blocks-wrap"><!-- wp:uagb/advanced-heading {"block_id":"bacd11a8","classMigrate":true,"headingAlign":"center","headingAlignTablet":"center","headingColor":"#ffffff","headingTag":"h1","blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockTopPaddingTablet":0,"blockRightPaddingTablet":0,"blockLeftPaddingTablet":0,"blockBottomPaddingTablet":0,"blockTopPaddingMobile":0,"blockRightPaddingMobile":0,"blockLeftPaddingMobile":0,"blockBottomPaddingMobile":0,"blockTopMargin":0,"blockRightMargin":0,"blockLeftMargin":0,"blockBottomMargin":0,"blockTopMarginTablet":0,"blockRightMarginTablet":0,"blockLeftMarginTablet":0,"blockBottomMarginTablet":0,"blockTopMarginMobile":0,"blockRightMarginMobile":0,"blockLeftMarginMobile":0,"blockBottomMarginMobile":0} -->
<div class="wp-block-uagb-advanced-heading uagb-block-bacd11a8"><h1 class="uagb-heading-text">اتصل بنا</h1></div>
<!-- /wp:uagb/advanced-heading --></div></div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/container {"block_id":"bb0d8871","directionDesktop":"row","alignItemsDesktop":"stretch","alignItemsTablet":"stretch","alignItemsMobile":"stretch","backgroundType":"color","backgroundColor":"var(--ast-global-color-5)","topPaddingDesktop":100,"bottomPaddingDesktop":100,"leftPaddingDesktop":40,"rightPaddingDesktop":40,"topPaddingTablet":80,"bottomPaddingTablet":80,"leftPaddingTablet":32,"rightPaddingTablet":32,"topPaddingMobile":64,"bottomPaddingMobile":64,"leftPaddingMobile":24,"rightPaddingMobile":24,"paddingLink":false,"topMarginDesktop":0,"bottomMarginDesktop":0,"leftMarginDesktop":0,"rightMarginDesktop":0,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"marginLink":false,"variationSelected":true,"rowGapTablet":0,"rowGapMobile":50,"columnGapDesktop":100,"columnGapTablet":60,"isBlockRootParent":true,"equalHeight":true} -->
<div class="wp-block-uagb-container uagb-block-bb0d8871 alignfull uagb-is-root-container"><div class="uagb-container-inner-blocks-wrap"><!-- wp:uagb/container {"block_id":"57120b1b","widthDesktop":50,"topPaddingDesktop":0,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"paddingLink":false,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"variationSelected":true,"rowGapTablet":0,"columnGapTablet":0,"widthSetByUser":true} -->
<div class="wp-block-uagb-container uagb-block-57120b1b"><!-- wp:uagb/info-box {"classMigrate":true,"headingAlign":"left","headingAlignTablet":"left","headingColor":"var(--ast-global-color-2)","subHeadingColor":"var(--ast-global-color-3)","prefixColor":"var(--ast-global-color-1)","prefixFontWeight":"500","prefixTransform":"uppercase","headingTag":"h2","headSpace":24,"subHeadSpace":0,"block_id":"3c3b8452","showCtaIcon":false,"seperatorStyle":"solid","seperatorColor":"var(--ast-global-color-6)","seperatorWidth":100,"seperatorThickness":1,"ctaText":"Get Started Now","ctaTransform":"uppercase","ctaBtnLinkColor":"","ctaBgColor":"","ctaBorderColor":"","ctaBorderStyle":"","showIcon":false,"showDesc":false,"paddingspacingLink":true,"paddingBtnTop":0,"paddingBtnBottom":0,"paddingBtnLeft":0,"paddingBtnRight":0,"prefixTopMargin":0,"prefixRightMargin":0,"prefixSpace":20,"prefixLeftMargin":0,"prefixMarginTopTablet":0,"prefixMarginRightTablet":0,"prefixTabletSpace":10,"prefixMarginLeftTablet":0,"prefixMarginTopMobile":0,"prefixMarginRightMobile":0,"prefixMobileSpace":10,"prefixMarginLeftMobile":0,"prefixLetterSpacing":2,"headTopMargin":0,"headRightMargin":0,"headLeftMargin":0,"headMarginTopTablet":0,"headMarginRightTablet":0,"headTabletSpace":24,"headMarginLeftTablet":0,"headMarginTopMobile":0,"headMarginRightMobile":0,"headMobileSpace":24,"headMarginLeftMobile":0,"blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockTopPaddingTablet":0,"blockRightPaddingTablet":0,"blockLeftPaddingTablet":0,"blockBottomPaddingTablet":0,"blockTopPaddingMobile":0,"blockRightPaddingMobile":0,"blockLeftPaddingMobile":0,"blockBottomPaddingMobile":0,"blockPaddingLink":false,"separatorMarginTopTablet":0,"separatorMarginRightTablet":0,"seperatorTabletSpace":0,"separatorMarginLeftTablet":0,"subHeadTopMargin":0,"subHeadRightMargin":0,"subHeadLeftMargin":0,"subHeadMarginTopTablet":0,"subHeadMarginRightTablet":0,"subHeadTabletSpace":0,"subHeadMarginLeftTablet":0,"subHeadMarginTopMobile":10,"subHeadMarginRightMobile":0,"subHeadMobileSpace":0,"subHeadMarginLeftMobile":0,"btnBorderTopWidth":1,"btnBorderLeftWidth":1,"btnBorderRightWidth":1,"btnBorderBottomWidth":1,"btnBorderTopLeftRadius":0,"btnBorderTopRightRadius":0,"btnBorderBottomLeftRadius":0,"btnBorderBottomRightRadius":0,"btnBorderStyle":"none","btnBorderColor":"#333"} -->
<div class="wp-block-uagb-info-box uagb-block-3c3b8452 uagb-infobox__content-wrap  uagb-infobox-icon-above-title uagb-infobox-image-valign-top"><div class="uagb-ifb-content"><div class="uagb-ifb-title-wrap"><h2 class="uagb-ifb-title">للتواصل معنا، يرجى استخدام المعلومات التالية</h2></div><div class="uagb-ifb-separator"></div></div></div>
<!-- /wp:uagb/info-box -->

<!-- wp:uagb/container {"block_id":"c7f05599","backgroundType":"color","backgroundColor":"","topPaddingDesktop":24,"bottomPaddingDesktop":10,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":24,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":24,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"paddingLink":false,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"marginLink":false,"variationSelected":true,"rowGapDesktop":32,"rowGapTablet":24,"rowGapMobile":30} -->
<div class="wp-block-uagb-container uagb-block-c7f05599"><!-- wp:uagb/advanced-heading {"block_id":"db1db25f","classMigrate":true,"headingDescToggle":true,"headingAlignTablet":"left","headingColor":"var(--ast-global-color-2)","subHeadingColor":"","headingTag":"div","headSpace":0,"headSpaceMobile":0,"headSpaceTablet":0,"subHeadSpace":0,"headFontWeight":"500","headTransform":"","headFontSize":20,"headFontSizeTablet":18,"headFontSizeMobile":16,"subHeadTransform":"","blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockTopPaddingTablet":0,"blockRightPaddingTablet":0,"blockLeftPaddingTablet":0,"blockBottomPaddingTablet":0,"blockTopPaddingMobile":0,"blockRightPaddingMobile":0,"blockLeftPaddingMobile":0,"blockBottomPaddingMobile":0,"blockTopMargin":0,"blockRightMargin":0,"blockLeftMargin":0,"blockBottomMargin":0,"blockTopMarginTablet":0,"blockRightMarginTablet":0,"blockLeftMarginTablet":0,"blockBottomMarginTablet":0,"blockTopMarginMobile":0,"blockRightMarginMobile":0,"blockLeftMarginMobile":0,"blockBottomMarginMobile":0} -->
<div class="wp-block-uagb-advanced-heading uagb-block-db1db25f"><div class="uagb-heading-text">العنوان</div><p class="uagb-desc-text">دمشق - الميدان</p></div>
<!-- /wp:uagb/advanced-heading -->

<!-- wp:uagb/advanced-heading {"block_id":"c3b421fe","classMigrate":true,"headingDescToggle":true,"headingAlignTablet":"left","headingColor":"var(--ast-global-color-2)","subHeadingColor":"","headingTag":"div","headSpace":0,"headSpaceMobile":0,"headSpaceTablet":0,"subHeadSpace":0,"headFontWeight":"500","headTransform":"","headFontSize":20,"headFontSizeTablet":18,"headFontSizeMobile":16,"subHeadTransform":"","blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockTopPaddingTablet":0,"blockRightPaddingTablet":0,"blockLeftPaddingTablet":0,"blockBottomPaddingTablet":0,"blockTopPaddingMobile":0,"blockRightPaddingMobile":0,"blockLeftPaddingMobile":0,"blockBottomPaddingMobile":0,"blockTopMargin":0,"blockRightMargin":0,"blockLeftMargin":0,"blockBottomMargin":0,"blockTopMarginTablet":0,"blockRightMarginTablet":0,"blockLeftMarginTablet":0,"blockBottomMarginTablet":0,"blockTopMarginMobile":0,"blockRightMarginMobile":0,"blockLeftMarginMobile":0,"blockBottomMarginMobile":0} -->
<div class="wp-block-uagb-advanced-heading uagb-block-c3b421fe"><div class="uagb-heading-text">الهاتف</div><p class="uagb-desc-text">22222222222</p></div>
<!-- /wp:uagb/advanced-heading -->

<!-- wp:uagb/advanced-heading {"block_id":"bcf170a6","classMigrate":true,"headingDescToggle":true,"headingAlignTablet":"left","headingColor":"var(--ast-global-color-2)","subHeadingColor":"","headingTag":"div","headSpace":0,"headSpaceMobile":0,"headSpaceTablet":0,"subHeadSpace":0,"headFontWeight":"500","headTransform":"","headFontSize":20,"headFontSizeTablet":18,"headFontSizeMobile":16,"subHeadTransform":"","blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockTopPaddingTablet":0,"blockRightPaddingTablet":0,"blockLeftPaddingTablet":0,"blockBottomPaddingTablet":0,"blockTopPaddingMobile":0,"blockRightPaddingMobile":0,"blockLeftPaddingMobile":0,"blockBottomPaddingMobile":0,"blockTopMargin":0,"blockRightMargin":0,"blockLeftMargin":0,"blockBottomMargin":0,"blockTopMarginTablet":0,"blockRightMarginTablet":0,"blockLeftMarginTablet":0,"blockBottomMarginTablet":0,"blockTopMarginMobile":0,"blockRightMarginMobile":0,"blockLeftMarginMobile":0,"blockBottomMarginMobile":0} -->
<div class="wp-block-uagb-advanced-heading uagb-block-bcf170a6"><div class="uagb-heading-text">البريد الإلكتروني</div><p class="uagb-desc-text">aaaaa@aaa.com</p></div>
<!-- /wp:uagb/advanced-heading --></div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/separator {"block_id":"e6f07a50","separatorBorderHeight":1,"separatorBorderHeightMobile":1,"separatorBorderHeightTablet":1,"separatorColor":"var(--ast-global-color-6)","separatorHeight":0,"separatorHeightMobile":0,"separatorHeightTablet":0,"blockTopPadding":20,"blockBottomPadding":20,"blockTopPaddingTablet":15,"blockBottomPaddingTablet":15,"blockTopPaddingMobile":15,"blockBottomPaddingMobile":15,"blockPaddingUnit":"px","blockPaddingUnitTablet":"px","blockPaddingUnitMobile":"px"} -->
<div class="wp-block-uagb-separator uagb-block-e6f07a50"><div class="uagb-separator-spacing-wrapper"><div class="wp-block-uagb-separator__inner" style="--my-background-image:"></div></div></div>
<!-- /wp:uagb/separator -->

<!-- wp:uagb/icon-list {"block_id":"0c4edb29","classMigrate":true,"childMigrate":true,"alignTablet":"left","parentIcon":"","gap":20,"size":22,"hideLabel":true,"icon_layout":"horizontal","iconColor":"var(--ast-global-color-2)","iconHoverColor":"var(--ast-global-color-1)","iconBgHoverColor":"","iconBorderHoverColor":"","blockTopMargin":0,"blockRightMargin":0,"blockLeftMargin":0,"blockBottomMargin":0,"blockTopPadding":0,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingLink":false} -->
<div class="wp-block-uagb-icon-list uagb-block-0c4edb29"><div class="uagb-icon-list__wrap"><!-- wp:uagb/icon-list-child {"block_id":"10f8a12c","hideLabel":true,"icon":"facebook","link":"https://facebook.com/sabaya.mk.up/","target":true,"disableLink":true,"fromParentIcon":"","imageSizeChild":22} -->
<div class="wp-block-uagb-icon-list-child uagb-block-10f8a12c"><a target="_blank" aria-label="List item" rel="noopener noreferrer" href="https://facebook.com/sabaya.mk.up/"> </a><span class="uagb-icon-list__source-wrap"><svg xmlns="https://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.8 90.69 226.4 209.3 245V327.7h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.3 482.4 504 379.8 504 256z"></path></svg></span></div>
<!-- /wp:uagb/icon-list-child -->

<!-- wp:uagb/icon-list-child {"block_id":"295d1f74","hideLabel":true,"link":"","target":true,"disableLink":true,"fromParentIcon":"","imageSizeChild":22} -->
<div class="wp-block-uagb-icon-list-child uagb-block-295d1f74"><a target="_blank" aria-label="List item" rel="noopener noreferrer" href=""> </a></div>
<!-- /wp:uagb/icon-list-child -->







</div></div>
<!-- /wp:uagb/icon-list --></div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/container {"block_id":"08eea032","widthDesktop":50,"backgroundType":"color","backgroundColor":"","topPaddingDesktop":0,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":24,"topMarginDesktop":0,"bottomMarginDesktop":0,"leftMarginDesktop":0,"rightMarginDesktop":0,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"marginLink":false,"variationSelected":true,"rowGapTablet":0,"columnGapTablet":0,"widthSetByUser":true,"containerBorderTopLeftRadius":0,"containerBorderTopRightRadius":0,"containerBorderBottomLeftRadius":0,"containerBorderBottomRightRadius":0} -->
<div class="wp-block-uagb-container uagb-block-08eea032"><!-- wp:shortcode -->
[sureforms id='1584']
<!-- /wp:shortcode --></div>
<!-- /wp:uagb/container --></div></div>
<!-- /wp:uagb/container -->

<!-- wp:block {"ref":293} /-->
</div>
<?php get_footer(); ?>